// apps/frontend-react/src/features/setup/steps/Step6HealthCheck.tsx
import { useEffect, useRef, useState } from 'react';
import axios from 'axios';
import { toast } from 'sonner';
import { Button } from '@/components/ui/button';
import { setupGateway } from '@/features/setup/setup-gateway';
import type { HealthCheckResult } from '@/features/setup/setup.types';

interface Props {
  onComplete: () => void;
}

// Mirrors the Vue 3 wizard's 4-second debounce on "Verificar novamente"
// to prevent hammering /setup/health-check (backend rate-limits anyway).
const RETRY_COOLDOWN_MS = 4000;

const SERVICES = [
  { key: 'postgres', label: 'PostgreSQL' },
  { key: 'redis', label: 'Redis' },
  { key: 'clickhouse', label: 'ClickHouse' },
  { key: 'rabbitmq', label: 'RabbitMQ' },
  { key: 's3', label: 'S3 / MinIO' },
  { key: 'smtp', label: 'SMTP' },
] as const;

type ServiceKey = (typeof SERVICES)[number]['key'];

export function Step6HealthCheck({ onComplete }: Props) {
  const [loading, setLoading] = useState(false);
  const [completing, setCompleting] = useState(false);
  const [results, setResults] = useState<HealthCheckResult | null>(null);
  const [retryOnCooldown, setRetryOnCooldown] = useState(false);
  const [showConfirm, setShowConfirm] = useState(false);
  const cooldownRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  async function runCheck() {
    if (loading) return;
    setLoading(true);
    setRetryOnCooldown(true);
    if (cooldownRef.current) clearTimeout(cooldownRef.current);
    cooldownRef.current = setTimeout(() => setRetryOnCooldown(false), RETRY_COOLDOWN_MS);
    try {
      const res = await setupGateway.healthCheck();
      setResults(res);
    } catch (err) {
      const msg =
        axios.isAxiosError(err) && err.response?.data?.message
          ? String(err.response.data.message)
          : 'Erro ao verificar serviços.';
      toast.error(msg);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    runCheck();
    return () => {
      if (cooldownRef.current) clearTimeout(cooldownRef.current);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  function handleComplete() {
    if (results?.allOk) {
      doComplete();
    } else {
      setShowConfirm(true);
    }
  }

  async function doComplete() {
    setShowConfirm(false);
    setCompleting(true);
    try {
      const data = results?.allOk
        ? {}
        : { skipReason: 'Administrador optou por concluir com serviços com falha.' };
      await setupGateway.advanceStep({ step: 6, data });
      onComplete();
    } catch (err) {
      const msg =
        axios.isAxiosError(err) && err.response?.data?.message
          ? String(err.response.data.message)
          : 'Erro ao concluir configuração.';
      toast.error(msg);
    } finally {
      setCompleting(false);
    }
  }

  const failingServices = results
    ? SERVICES.filter((s) => !results[s.key as ServiceKey].ok).map((s) => ({
        ...s,
        error: results[s.key as ServiceKey].error ?? '',
      }))
    : [];

  return (
    <div>
      {loading && !results && (
        <div className="text-muted-foreground flex items-center justify-center gap-2 py-8 text-sm">
          <div className="border-primary h-4 w-4 animate-spin rounded-full border-2 border-r-transparent" />
          <span>Verificando serviços...</span>
        </div>
      )}

      {results && (
        <>
          <div className="mb-6 space-y-2">
            {SERVICES.map((service) => {
              const r = results[service.key as ServiceKey];
              return (
                <div
                  key={service.key}
                  className={
                    'flex items-center justify-between rounded-lg border px-4 py-3 ' +
                    (r.ok
                      ? 'border-green-200 bg-green-50 dark:border-green-900/40 dark:bg-green-900/10'
                      : 'border-red-200 bg-red-50 dark:border-red-900/40 dark:bg-red-900/10')
                  }
                >
                  <span className="text-foreground text-sm font-medium">{service.label}</span>
                  <div className="flex items-center gap-2">
                    {r.ok ? (
                      <>
                        <span className="text-muted-foreground text-xs">{r.latencyMs}ms</span>
                        <span className="font-bold text-green-600">✓</span>
                      </>
                    ) : (
                      <>
                        <span
                          className="max-w-[180px] truncate text-xs text-red-600"
                          title={r.error}
                        >
                          {r.error}
                        </span>
                        <span className="font-bold text-red-600">✗</span>
                      </>
                    )}
                  </div>
                </div>
              );
            })}
          </div>

          <div className="flex items-center justify-between">
            <Button
              type="button"
              variant="secondary"
              disabled={loading || completing || retryOnCooldown}
              onClick={runCheck}
            >
              Verificar novamente
            </Button>
            <Button type="button" disabled={completing || loading} onClick={handleComplete}>
              {completing ? 'Concluindo...' : 'Concluir'}
            </Button>
          </div>
        </>
      )}

      {showConfirm && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 px-4">
          <div className="bg-card w-full max-w-sm rounded-2xl p-6 shadow-xl">
            <h3 className="text-foreground mb-2 text-base font-semibold">Serviços com falha</h3>
            <p className="text-muted-foreground mb-3 text-sm">
              Os serviços abaixo não responderam corretamente. A plataforma pode não funcionar como esperado até que sejam corrigidos:
            </p>
            <ul className="mb-4 space-y-1">
              {failingServices.map((s) => (
                <li key={s.key} className="flex items-center gap-2 text-sm text-red-600">
                  <span className="font-bold">✗</span>
                  {s.label}
                  {s.error && <span className="truncate text-xs text-red-400" title={s.error}> — {s.error}</span>}
                </li>
              ))}
            </ul>
            <p className="mb-5 rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-700 dark:border-amber-900/40 dark:bg-amber-900/10">
              Deseja concluir mesmo assim? Você poderá corrigir as configurações após o primeiro acesso.
            </p>
            <div className="flex justify-between gap-3">
              <Button type="button" variant="secondary" disabled={completing} onClick={() => setShowConfirm(false)}>
                Cancelar
              </Button>
              <Button type="button" disabled={completing} onClick={doComplete}>
                {completing ? 'Concluindo...' : 'Concluir'}
              </Button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// apps/msgops-manager-frontend/src/pages/SetupPage/steps/Step6HealthCheck.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import { BmsButton } from '../../../components';
import { setupGateway, HealthCheckResult } from '../../../gateways/Setup';
import { showToast } from '../../../utils/showToast';

const emit = defineEmits<{ (e: 'step-complete'): void }>();

const loading = ref(false);
const completing = ref(false);
const results = ref<HealthCheckResult | null>(null);
const retryOnCooldown = ref(false);
const showConfirm = ref(false);

const services = [
  { key: 'postgres' as const, label: 'PostgreSQL' },
  { key: 'redis' as const, label: 'Redis' },
  { key: 'clickhouse' as const, label: 'ClickHouse' },
  { key: 'rabbitmq' as const, label: 'RabbitMQ' },
  { key: 's3' as const, label: 'S3 / MinIO' },
  { key: 'smtp' as const, label: 'SMTP' },
];

const failingServices = computed(() => {
  const r = results.value;
  if (!r) return [];
  return services
    .filter((s) => !r[s.key].ok)
    .map((s) => ({ ...s, error: r[s.key].error ?? '' }));
});

async function runCheck() {
  loading.value = true;
  retryOnCooldown.value = true;
  setTimeout(() => {
    retryOnCooldown.value = false;
  }, 4000);
  try {
    results.value = await setupGateway.healthCheck();
  } catch (e: any) {
    showToast({ type: 'error', description: e?.response?.data?.message || 'Erro ao verificar serviços.' });
  } finally {
    loading.value = false;
  }
}

function handleComplete() {
  if (results.value?.allOk) {
    doComplete();
  } else {
    showConfirm.value = true;
  }
}

async function doComplete() {
  showConfirm.value = false;
  completing.value = true;
  try {
    const data = results.value?.allOk
      ? {}
      : { skipReason: 'Administrador optou por concluir com serviços com falha.' };
    await setupGateway.advanceStep(6, data);
    emit('step-complete');
  } catch (e: any) {
    showToast({ type: 'error', description: e?.response?.data?.message || 'Erro ao concluir configuração.' });
  } finally {
    completing.value = false;
  }
}

onMounted(() => runCheck());
</script>

<template>
  <div>
    <div v-if="loading" class="tw-flex tw-items-center tw-gap-2 tw-py-8 tw-justify-center tw-text-gray">
      <v-progress-circular indeterminate size="20" width="2" color="primary" />
      <span class="tw-text-sm">Verificando serviços...</span>
    </div>

    <div v-else-if="results">
      <div class="tw-space-y-2 tw-mb-6">
        <div
          v-for="service in services"
          :key="service.key"
          class="tw-flex tw-items-center tw-justify-between tw-rounded-lg tw-border tw-px-4 tw-py-3"
          :class="results[service.key].ok ? 'tw-border-green-200 tw-bg-green-50' : 'tw-border-red-200 tw-bg-red-50'"
        >
          <span class="tw-text-sm tw-font-medium tw-text-main-gray">{{ service.label }}</span>
          <div class="tw-flex tw-items-center tw-gap-2">
            <span v-if="results[service.key].ok" class="tw-text-xs tw-text-gray">
              {{ results[service.key].latencyMs }}ms
            </span>
            <span v-else class="tw-text-xs tw-text-red-600 tw-max-w-[180px] tw-truncate" :title="results[service.key].error">
              {{ results[service.key].error }}
            </span>
            <span v-if="results[service.key].ok" class="tw-text-green-600 tw-font-bold">✓</span>
            <span v-else class="tw-text-red-600 tw-font-bold">✗</span>
          </div>
        </div>
      </div>

      <div class="tw-flex tw-justify-between tw-items-center">
        <BmsButton name="btn-retry" type="button" variant="secondary" :disabled="loading || completing || retryOnCooldown" @click="runCheck">
          Verificar novamente
        </BmsButton>
        <BmsButton
          name="btn-complete"
          type="button"
          variant="primary"
          :disabled="completing || loading"
          @click="handleComplete"
        >
          Concluir
        </BmsButton>
      </div>
    </div>

    <!-- Confirmation modal when services are failing -->
    <div
      v-if="showConfirm"
      class="tw-fixed tw-inset-0 tw-z-50 tw-flex tw-items-center tw-justify-center tw-bg-black/40 tw-px-4"
    >
      <div class="tw-w-full tw-max-w-sm tw-rounded-2xl tw-bg-white tw-p-6 tw-shadow-xl">
        <h3 class="tw-text-base tw-font-semibold tw-text-main-gray tw-mb-2">
          Serviços com falha
        </h3>
        <p class="tw-text-sm tw-text-gray tw-mb-3">
          Os serviços abaixo não responderam corretamente. A plataforma pode não funcionar como esperado até que sejam corrigidos:
        </p>
        <ul class="tw-mb-4 tw-space-y-1">
          <li
            v-for="s in failingServices"
            :key="s.key"
            class="tw-flex tw-items-center tw-gap-2 tw-text-sm tw-text-red-600"
          >
            <span class="tw-font-bold">✗</span>
            {{ s.label }}
            <span class="tw-text-xs tw-text-red-400 tw-truncate" :title="s.error">
              — {{ s.error }}
            </span>
          </li>
        </ul>
        <p class="tw-text-xs tw-text-amber-600 tw-bg-amber-50 tw-border tw-border-amber-200 tw-rounded-lg tw-px-3 tw-py-2 tw-mb-5">
          Deseja concluir mesmo assim? Você poderá corrigir as configurações após o primeiro acesso.
        </p>
        <div class="tw-flex tw-justify-between tw-gap-3">
          <BmsButton name="btn-confirm-cancel" type="button" variant="secondary" :disabled="completing" @click="showConfirm = false">
            Cancelar
          </BmsButton>
          <BmsButton name="btn-confirm-ok" type="button" variant="primary" :disabled="completing" @click="doComplete">
            Concluir
          </BmsButton>
        </div>
      </div>
    </div>
  </div>
</template>
