// apps/frontend-react/src/features/setup/steps/Step3Domain.tsx
import { useState, type FormEvent } from 'react';
import axios from 'axios';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { setupGateway } from '@/features/setup/setup-gateway';

interface Props {
  onComplete: () => void;
}

function isValidUrl(value: string): boolean {
  try {
    const u = new URL(value);
    return u.protocol === 'http:' || u.protocol === 'https:';
  } catch {
    return false;
  }
}

export function Step3Domain({ onComplete }: Props) {
  const [baseUrl, setBaseUrl] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function handleSubmit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault();
    setError(null);
    if (!isValidUrl(baseUrl.trim())) {
      setError('URL inválida. Ex: https://app.empresa.com');
      return;
    }
    setSubmitting(true);
    try {
      await setupGateway.advanceStep({ step: 3, data: { baseUrl: baseUrl.trim() } });
      onComplete();
    } catch (err) {
      const msg =
        axios.isAxiosError(err) && err.response?.data?.message
          ? String(err.response.data.message)
          : 'Erro ao salvar URL base.';
      setError(msg);
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <form onSubmit={handleSubmit} noValidate className="flex flex-col gap-4">
      <div className="flex flex-col gap-1.5">
        <Label htmlFor="setup-base-url">URL base da plataforma</Label>
        <Input
          id="setup-base-url"
          autoFocus
          placeholder="https://app.empresa.com"
          value={baseUrl}
          onChange={(e) => setBaseUrl(e.target.value)}
          disabled={submitting}
        />
        <p className="text-muted-foreground text-xs">
          Usada em links de e-mails, redirecionamentos e integrações externas.
        </p>
      </div>

      {error && (
        <Alert variant="destructive">
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      )}

      <div className="flex justify-end">
        <Button type="submit" disabled={submitting}>
          {submitting ? 'Salvando...' : 'Salvar e continuar'}
        </Button>
      </div>
    </form>
  );
}

// apps/msgops-manager-frontend/src/pages/SetupPage/steps/Step3Domain.vue
<script setup lang="ts">
import { useForm } from 'vee-validate';
import { toTypedSchema } from '@vee-validate/zod';
import { z } from 'zod';
import { BmsTextField, BmsButton } from '../../../components';
import { setupGateway } from '../../../gateways/Setup';
import { showToast } from '../../../utils/showToast';

const emit = defineEmits<{ 'step-complete': [] }>();

const schema = toTypedSchema(
  z.object({
    baseUrl: z.string().url('URL inválida. Ex: https://app.empresa.com'),
  })
);

const { handleSubmit, isSubmitting } = useForm({
  initialValues: { baseUrl: '' },
  validationSchema: schema,
});

const onSubmit = handleSubmit(async (values) => {
  try {
    await setupGateway.advanceStep(3, { baseUrl: values.baseUrl });
    emit('step-complete');
  } catch (e: any) {
    showToast({ type: 'error', description: e?.response?.data?.message || 'Erro ao salvar URL base.' });
  }
});
</script>

<template>
  <form @submit.prevent="onSubmit">
    <BmsTextField
      name="baseUrl"
      label="URL base da plataforma"
      placeholder="https://app.empresa.com"
    />
    <p class="tw-mb-4 tw-text-xs tw-text-gray">
      Usada em links de emails, redirecionamentos e integrações externas.
    </p>

    <div class="tw-flex tw-justify-end">
      <BmsButton name="btn-step3" type="submit" variant="primary" :disabled="isSubmitting">
        Salvar e continuar
      </BmsButton>
    </div>
  </form>
</template>
