// apps/frontend-react/src/features/setup/steps/Step1Admin.tsx
import { useState, type FormEvent } from 'react';
import axios from 'axios';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { setupGateway } from '@/features/setup/setup-gateway';
import { login } from '@/features/auth/use-auth';

const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

interface Props {
  onComplete: () => void;
}

export function Step1Admin({ onComplete }: Props) {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  function validate(): string | null {
    if (name.trim().length < 2) return 'Informe seu nome completo.';
    if (!EMAIL_RE.test(email)) return 'E-mail inválido.';
    if (password.length < 8) return 'A senha deve ter pelo menos 8 caracteres.';
    if (password !== confirmPassword) return 'As senhas não conferem.';
    return null;
  }

  async function handleSubmit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault();
    setError(null);
    const localErr = validate();
    if (localErr) {
      setError(localErr);
      return;
    }
    setSubmitting(true);
    try {
      await setupGateway.advanceStep({
        step: 1,
        data: { name: name.trim(), email: email.trim().toLowerCase(), password },
      });
      // Auto-login: subsequent steps may need an authenticated session and the
      // operator just typed valid credentials. Mirrors Vue 3 wizard behavior.
      try {
        await login(email.trim().toLowerCase(), password);
      } catch {
        // Auto-login is best-effort. Steps 2-6 are public on the backend, so
        // a failure here doesn't block the wizard.
      }
      onComplete();
    } catch (err) {
      const msg =
        axios.isAxiosError(err) && err.response?.data?.message
          ? String(err.response.data.message)
          : 'Erro ao criar administrador.';
      setError(msg);
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <form onSubmit={handleSubmit} noValidate className="flex flex-col gap-4">
      <div className="flex flex-col gap-1.5">
        <Label htmlFor="setup-admin-name">Nome completo</Label>
        <Input
          id="setup-admin-name"
          autoFocus
          autoComplete="name"
          placeholder="João Silva"
          value={name}
          onChange={(e) => setName(e.target.value)}
          disabled={submitting}
        />
      </div>

      <div className="flex flex-col gap-1.5">
        <Label htmlFor="setup-admin-email">E-mail</Label>
        <Input
          id="setup-admin-email"
          type="email"
          autoComplete="email"
          placeholder="admin@empresa.com"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          disabled={submitting}
        />
      </div>

      <div className="flex flex-col gap-1.5">
        <Label htmlFor="setup-admin-password">Senha</Label>
        <Input
          id="setup-admin-password"
          type="password"
          autoComplete="new-password"
          placeholder="Mínimo 8 caracteres"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          disabled={submitting}
        />
      </div>

      <div className="flex flex-col gap-1.5">
        <Label htmlFor="setup-admin-confirm">Confirmar senha</Label>
        <Input
          id="setup-admin-confirm"
          type="password"
          autoComplete="new-password"
          placeholder="Repita a senha"
          value={confirmPassword}
          onChange={(e) => setConfirmPassword(e.target.value)}
          disabled={submitting}
        />
      </div>

      {error && (
        <Alert variant="destructive">
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      )}

      <div className="mt-2 flex justify-end">
        <Button type="submit" disabled={submitting}>
          {submitting ? 'Criando...' : 'Criar e continuar'}
        </Button>
      </div>
    </form>
  );
}

// apps/msgops-manager-frontend/src/pages/SetupPage/steps/Step1Admin.vue
<script setup lang="ts">
import { useForm } from 'vee-validate';
import { toTypedSchema } from '@vee-validate/zod';
import { z } from 'zod';
import { BmsTextField, BmsButton } from '../../../components';
import { setupGateway } from '../../../gateways/Setup';
import { showToast } from '../../../utils/showToast';

const emit = defineEmits<{ (e: 'step-complete'): void }>();

const schema = toTypedSchema(
  z.object({
    name: z.string().min(2, 'Nome obrigatório'),
    email: z.string().email('Email inválido'),
    password: z.string().min(8, 'Mínimo 8 caracteres'),
    confirmPassword: z.string(),
  }).refine((d) => d.password === d.confirmPassword, {
    message: 'As senhas não conferem',
    path: ['confirmPassword'],
  })
);

const { handleSubmit, isSubmitting } = useForm({
  initialValues: { name: '', email: '', password: '', confirmPassword: '' },
  validationSchema: schema,
});

const onSubmit = handleSubmit(async (values) => {
  try {
    await setupGateway.advanceStep(1, { name: values.name, email: values.email, password: values.password });
    emit('step-complete');
  } catch (e: any) {
    showToast({ type: 'error', description: e?.response?.data?.message || 'Erro ao criar administrador.' });
  }
});
</script>

<template>
  <form @submit.prevent="onSubmit">
    <BmsTextField name="name" label="Nome completo" placeholder="João Silva" />
    <BmsTextField name="email" label="Email" type="email" placeholder="admin@empresa.com" />
    <BmsTextField name="password" label="Senha" type="password" placeholder="Mínimo 8 caracteres" />
    <BmsTextField name="confirmPassword" label="Confirmar senha" type="password" placeholder="Repita a senha" />

    <div class="tw-mt-6 tw-flex tw-justify-end">
      <BmsButton name="btn-step1" type="submit" variant="primary" :disabled="isSubmitting">
        Criar e continuar
      </BmsButton>
    </div>
  </form>
</template>
